app:
    resource: @AppBundle/Controller/
    type:     annotation

episodes:
    type: rest
    resource: AppBundle\Controller\EpisodesController
shows:
    type: rest
    resource: AppBundle\Controller\ShowsController