app:
    resource: @AppBundle/Controller/
    type:     annotation

categories:
    type: rest
    resource: AppBundle\Controller\CategoriesController

shows:
    type: rest
    resource: AppBundle\Controller\ShowsController

episodes:
    type: rest
    resource: AppBundle\Controller\EpisodesController
