<?php
namespace AppBundle\Entity;

use AppBundle\Helper\ListParameters;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends ResourceRepository
{
    /**
     * @param ListParameters $params
     *
     * @return \Knp\Component\Pager\Pagination\PaginationInterface
     */
    public function getList(ListParameters $params)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('c')
            ->from('AppBundle:Category', 'c')
            ->orderBy('c.sort', 'ASC');

        // Modified from
        $qb->where('c.modified >= :from');
        $qb->setParameter('from', $params->getFrom());

        $categories = $this->getPaginator()->paginate($qb, $params->getPage(), $params->getLimit());

        return $categories;
    }

    /**
     * @param int $id
     *
     * @return Category
     */
    public function getOne($id)
    {
        /**
         * @var \AppBundle\Entity\Category $category
         */
        $category = $this->findOneBy(['id' => $id]);

        return $category;
    }

    public function getByUid($uid)
    {
        /**
         * @var \AppBundle\Entity\Category $category
         */
        $category = $this->findOneBy(['uid' => $uid]);

        return $category;
    }
}
