<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use AppBundle\Module\Youtube\ChannelSelector;
use AppBundle\Module\Youtube\Template;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends EntityRepository
{
    public function getByProgram($program)
    {
        $programRegex = '~^[A-Z]{4}$~';
        if (preg_match($programRegex, $program)) {
            $query = $this->getEntityManager()
                          ->createQuery(
                           'SELECT v, p FROM AppBundle:Episode v
                             JOIN v.program p
                             WHERE p.code = :program
                             ORDER BY v.publish ASC')
                          ->setParameter('program', $program);
        } else {
            $query = $this->getEntityManager()
                          ->createQuery(
                           'SELECT v FROM AppBundle:Episode v
                             WHERE v.program = :program
                             ORDER BY v.publish ASC')
                          ->setParameter('program', $program);
        }

        $videos = $query->getResult();
        return $videos;
    }

    public function getByCode($code)
    {
        $query = $this->getEntityManager()
                      ->createQuery(
                       'SELECT v FROM AppBundle:Episode v
                         WHERE v.code = :code')
                      ->setMaxResults(1)
                      ->setParameter('code', $code);
        /**
         * @var \AppBundle\Entity\Episode $video
         */
        try {
            $video = $query->getSingleResult();
        } catch(NoResultException $e) {
            $video = new Episode();
        }

        return $video;
    }

    public function getForTrash($checked)
    {
        $programRepo = $this->getEntityManager()->getRepository('AppBundle:Show');
        $mh = $programRepo->findOneBy(['code' => 'MHKU']);

        $query = $this->getEntityManager()->createQuery(
                       'SELECT v FROM AppBundle:Episode v
                         WHERE v.id NOT IN (:checked)
                           AND v.program = :program
                           AND v.trash = 0')
                      ->setParameter('checked', $checked)
                      ->setParameter('program', $mh);

        $videos = $query->getResult();
        return $videos;
    }
}
