<?php
namespace AppBundle\Entity;

use AppBundle\Helper\ListParameters;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends ResourceRepository
{
    /**
     * @param ListParameters $params
     *
     * @return \Knp\Component\Pager\Pagination\PaginationInterface
     */
    public function getList(ListParameters $params)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s')
            ->from('AppBundle:Season', 's')
            ->orderBy('s.sort', 'ASC');

        $showId = $params->get('showId');
        if (null !== $showId) {
            $qb->where('s.show = :show');
            $qb->setParameter('show', $showId);
        }

        if ($this->getPaginator()) {
            $seasons = $this->getPaginator()->paginate($qb, $params->getPage(), $params->getLimit());
        } else {
            $seasons = $qb->getQuery()->getResult();
        }

        return $seasons;
    }

    /**
     * @param Show $show
     * @param string $uid
     *
     * @return Season
     */
    public function getOne(Show $show, $uid)
    {
        /**
         * @var \AppBundle\Entity\Season $season
         */
        $season = $this->findOneBy(['show' => $show, 'uid' => $uid]);

        return $season;
    }
}
