<?php
namespace AppBundle\Entity;

use AppBundle\Helper\ListParameters;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends ResourceRepository
{
    /**
     * @param ListParameters $params
     *
     * @return \Knp\Component\Pager\Pagination\PaginationInterface
     */
    public function getList(ListParameters $params)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s')
            ->from('AppBundle:Season', 's')
            ->orderBy('s.sort', 'ASC');

        $seasons = $this->getPaginator()->paginate($qb, $params->getPage(), $params->getLimit());

        return $seasons;
    }

    /**
     * @param string $uid
     *
     * @return Season
     */
    public function getOne($uid)
    {
        /**
         * @var \AppBundle\Entity\Season $season
         */
        $season = $this->findOneBy(['uid' => $uid]);

        return $season;
    }
}
