<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Orm\NoResultException;

/**
 * SharedProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedProgramRepository extends EntityRepository
{
    public function getByCode($code, $createNew = false)
    {
        $query = $this->getEntityManager()
                      ->createQuery(
                       'SELECT p FROM HopeMqBundle:SharedProgram p
                         WHERE p.code = :code')
                      ->setMaxResults(1)
                      ->setParameter('code', $code);
        /**
         * @var \AppBundle\Entity\SharedProgram $program
         */
        try {
            $program = $query->getSingleResult();
        } catch(NoResultException $e) {
            $program = $createNew ? new SharedProgram() : null;
        }

        return $program;
    }
}
