<?php

namespace AppBundle\Entity;

use AppBundle\Media\Media;
use AppBundle\Media\Image;
use Doctrine\ORM\EntityRepository;

/**
 * ShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowRepository extends EntityRepository
{
    /**
     * @return Show[]
     */
    public function getAll()
    {
        /**
         * @var \AppBundle\Entity\Show[] $shows
         */
        $shows = $this->findBy([], null, 10);
        foreach ($shows as $show) {
            $this->injectMedia($show);
        }

        return $shows;
    }

    /**
     * @param $code
     *
     * @return Show
     */
    public function getOne($code)
    {
        /**
         * @var \AppBundle\Entity\Show $show
         */
        $show = $this->findOneBy(['code' => $code]);
        $this->injectMedia($show);

        return $show;
    }

    private function injectMedia(Show $show)
    {
        $media = new Media();

        $image = new Image();
        $image->setUrl(sprintf('http://hope.ua/images/programs/%s.png', $show->getCode()));

        $media->setImage($image);

        $show->setMedia($media);
    }
}
