<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Orm\NoResultException;

/**
 * ShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowRepository extends EntityRepository
{
    /**
     * @return Show[]
     */
    public function getAll()
    {
        /**
         * @var \AppBundle\Entity\Show[] $shows
         */
        $shows = $this->findBy([], null, 10);

        return $shows;
    }

    /**
     * @param $code
     *
     * @return Show
     */
    public function getOne($code)
    {
        /**
         * @var \AppBundle\Entity\Show $show
         */
        $show = $this->findOneBy(['code' => $code]);

        return $show;
    }
}
